In [2]:
import mlflow

import pandas as pd

from sklearn.datasets import fetch_20newsgroups

from pycaret.classification import setup, compare_models

%load_ext dotenv
%dotenv

In [19]:
#df = pd.read_csv('../data/humor.csv')
#df_test = df.sample(n=10_000)
#df_train = df.drop(df_test.index).sample(n=30_000)
#df_train.to_csv('../data/train_data.csv', index=False)
#df_test.to_csv('../data/test_data.csv', index=False)

In [22]:
train_df = pd.read_csv('../data/train_data.csv')
train_df.head()

                                                text  humor
0  Why is saying  i'm sorry and i apologize mean ...   True
1  Why elisabeth badinter is wrong, and motherhoo...  False
2    What bee is forbidden to the muslims? haram-bee   True
3  Time to ramp it up for national romance awaren...  False
4  I like my women like i like my coffee wait a s...   True

In [24]:
s = setup(
  train_df,
  target='humor',
  log_experiment=True,
  log_plots=True,
  experiment_name='otus_pycaret'
)

In [25]:
best = compare_models()